### ISSUE TITLE
Source please

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/tinymce#13]
Thanx for importing this module. Much more usefull than Ckeditor.
One thing is missing though - or I overlook something: I need sometimes (actually often) to see the source for 'raw html' in order to copy code from one page to another. (I use the editor for my customers to be able to easily edit pages).

**Comment by indigoxela** [comment]
Hi @Egmund,

it's always good to have an alternative. :wink: 

To get the source code, you actually have different options, which also depend on the editor profile you chose.

The quickest: the "source code" button in the toolbar (here the default profile):

![source-code-button](https://github.com/backdrop-contrib/tinymce/assets/842066/6a2711eb-ed8d-4892-862a-0bb04ce7a8b8)

Another one: the "Source code" menu item (here the full profile):

![source-code-menuitem](https://github.com/backdrop-contrib/tinymce/assets/842066/bd8174a2-be48-40b2-b7de-3d11303fbdc1)

And finally, the filter formatting options (independently from editor):

![filter-raw-html](https://github.com/backdrop-contrib/tinymce/assets/842066/d6ee703c-0cb7-455c-b51a-04f9d033dac3)

**Comment by Egmund** [comment]
Thank you for the quick answer. I overlooked the first option - guess for me not obvious.
Now I can get to work on the site.
