### ISSUE TITLE
Convert line breaks into HTML not working for line breaks

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tinymce#14]
When using TinyMCE for editing and inserting a line break it fails by inserting `<br>` instead of `<br />` with the resulting display showing nothing and viewing the source showing nothing.

**Comment by indigoxela** [comment]
@iszmeez nice catch, but the problem isn't, how Tiny inserts the line breaks, but that the tag `<br>` isn't in the allowlist for filter.

As a quick fix you can add it manually by editing the "Limit allowed HTML tags" of your filter on admin/config/content/formats/YOUR_FILTER.

In the next release I will also update the default profiles in next release and add "br" to the builder tool.

**Comment by indigoxela** [comment]
A pull request is available for testing. Note that it has to run a config update.

**Comment by izmeez** [comment]
Thanks. The PR fixes the problem and I did run the core/update.php before testing it.
I did at first wonder if it was missing from the allowed tags but couldn't see that right away and when I saw the checkbox for "Convert line breaks into HTML" thought it might be something else.
Thanks, this fixes it. Unfortunately, I do not think I have permissions to add labels, yet.

**Comment by izmeez** [comment]
Just an aside, I don't know why but it seems some applications use `<br>` as TinyMCE does and others use `<br />` like Ckeditor does. I've never understood why the difference, maybe it's just historical?

**Comment by indigoxela** [comment]
@izmeez many thanks for testing and feedback. :+1:

Re ability to edit labels - ask in our Zulip chat to become member of the ... (hm, which team actually...). Someone there can help you.
