### ISSUE TITLE
Node edit window is large and not adjustable

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tinymce#26]
As title says the node edit window is large and not adjustable. This means, depending on the size of the browser window and the length of the node contents the editor toolbar may scroll up and out of view.

**Comment by indigoxela** [comment]
Depending on content, the edit area might be large, but surely that's adjustable. :wink:

If I get your request right, you'd prefer to turn the autoresize plugin off. You can do that on existing profiles by removing `autoresize` from the plugin list. Or create a new profile on admin/config/content/tinymce-builder with "Use autoresize" unchecked.

However, TinyMCE provides a lot more options to control editor area size:

- As mentioned, [the plugin](https://www.tiny.cloud/docs/tinymce/6/autoresize/) can be on or off
- There are also (among others) the options for "min_height" and "max_height" (follow above documentation link)
- With autoresize off, you can set dimensions to fixed values ([documentation](https://www.tiny.cloud/docs/tinymce/6/customize-ui/#set-the-editable-area-height))

Additonally, there's the option to use sticky toolbars, see [documentation for that](https://www.tiny.cloud/docs/tinymce/6/toolbar-configuration-options/#toolbar_sticky).

So, whatever you need, it's possible. (And, no, the builder will *not* provide each and every option via admin UI.) :wink:

**Comment by izmeez** [comment]
Thank you for identifying the setting causing the behaviour I am experiencing. As mentioned in another issue, this does not need to be added to the admin UI and can be changed in a custom JSON profile.

**Comment by indigoxela** [comment]
Toggling the autoresize plugin on or off _is_ available in the admin UI (as a checkbox).

**Comment by izmeez** [comment]
I took a look and do not seem to be able to find the checkbox for the autoresize plugin.

**Comment by indigoxela** [comment]
> I took a look and do not seem to be able to find the checkbox for the autoresize plugin.

Pretty prominently in the profile builder:

![autoresize-setting](https://github.com/backdrop-contrib/tinymce/assets/842066/a18de8a4-e6c6-41b6-a53f-9de4f2c68750)

**Comment by izmeez** [comment]
Sorry, looking in all the wrong places. Didn't look in the profile builder. Can't miss it there! Thanks.
