### ISSUE TITLE
Image upload via drag-and-drop

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/tinymce#3]
If it's very complicated... it gets a rather low priority.

UPDATE: it *is* complicated.
Not the PHP part (hook_menu for an upload url and a handler), not the Tiny settings part (images_file_types, images_upload_url, automatic_uploads).
But the communication won't work properly.

If using the default images_upload_handler, there's _zero_ option to display a proper message, when the image validation (server side) fails (only the http response code will show up).
Using a custom images_upload_handler (as officially documented) is pretty flaky (`n(... is undefined` :clown_face:), because of some stuff that happens _outside_ of the handler. Hard to debug with the minified js code.

Writing a complete Uploader class as replacement for the default seems out of scope.

Postponed until ... someone can fix it, or things get easier on TinyMCE API side.

**Comment by indigoxela** [comment]
Seems like I got it working, now, but need to do more testing with a fresher mind. :wink:

**Comment by yorkshire-pudding** [comment]
I've given it a test and seems to work well.  Thank you
