### ISSUE TITLE
Additions for modules list page

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tinymce#4]
There are two items for the /admin/modules/list page:

1. Add link button "Configure" to the /admin/config/content/formats
2. Add TinyMCE module to the User Interface group, /admin/modules/list#user-interface

**Comment by indigoxela** [comment]
Hi @izmeez,

good idea, done. (Although I'm not sure, if I can use "package" in my contrib module.) Many thanks for the hint. :+1:

**Comment by izmeez** [comment]
I am wondering if the changes you made are causing the duplication of the group "User Interface" on the admin/modules/list page? The two group buttons are also behaving oddly with some interaction between their displays. I have tried flushing caches to no avail.

![tinymce-module-group-duplicated](https://github.com/backdrop-contrib/tinymce/assets/6208775/605506f9-011a-4d96-977f-3c769218832c)

**Comment by izmeez** [comment]
I am using module_filter on the site, but it has been behaving fine.

**Comment by izmeez** [comment]
I have retested this as a fresh install on another site and this is not related to the TinyMCE module. My apologies for the distraction.
