### ISSUE TITLE
Conflicting function name with profile module

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/tinymce#44]
From our Zulip chat:

>  we've noticed that the function tinymce_profile_load($name) has a conflict with the module Profile, which has the hook_profile_load(). Any chance the function can be renamed?

https://github.com/backdrop-contrib/tinymce/blob/1.x-1.x/tinymce.module#L60

The easiest solution would be to strip the underscore...

`%tinymceprofile` would result in function `tinymceprofile_load`, which shouldn't conflict with anything else.

**Comment by avpaderno** [comment]
There is [`hook_load()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.api.php/function/hook_load/1), but that hook is invoked only for modules that implement a node content type. It would not be invoked for this module.
