### ISSUE TITLE
Fix Warning: Undefined array key "content_css"

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tinymce#6]
Testing latest code and settings page displays warning with php 8.1.17

`Warning: Undefined array key "content_css" in _tinymce_settings_form() (line 40 of tinymce.admin.inc)`

**Comment by izmeez** [comment]
Warning goes away when a path is entered for an enabled theme.

**Comment by indigoxela** [comment]
> Warning: Undefined array key "content_css"

Are you sure, you _uninstalled_ the module before updating via git?

As that's exactly the message you'll get, when a filter format has the old settings. In that case saving the format once (even with empty content_css setting) will fix it.

**Comment by izmeez** [comment]
No, I did not uninstall. I have tested again with both a fresh install and by uninstalling and re-enabling. I do not get the warning with either. However, when uninstalled and then re-enabling, I am surprised to see the content css path shows the last one I had entered.

**Comment by izmeez** [comment]
I am closing this issue.

**Comment by izmeez** [comment]
Maybe I should leave it open in case there are any comments on the observation:

> However, when uninstalled and then re-enabling, I am surprised to see the content css path shows the path I had entered before uninstalling.

**Comment by izmeez** [comment]
Further testing: uninstalled tinymce, and flushed caches and configured filter format to use ckeditor. Then enabled tinymce and configured filter formats to use tinymce and the content css appears with the default path and no warnings.

I think that covers it all. I am going to close this issue.
