### ISSUE TITLE
Add support for browser spellchecker if enabled

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tinymce#7]
The ckeditor module includes support for browser spellchecker if enabled such as with firefox browser, whereas the tinymce module does not. Can this be added? I can look up the lines that add this in ckeditor if that will help.

**Comment by indigoxela** [comment]
That's a good idea. Browser spellcheck is now enabled by default: be7df986

**Comment by izmeez** [comment]
The browser spell checker is active. However, I'm getting some weird behaviour. It does not appear to underline a misspelled word when a space is entered, only after the first letter of the next word is entered. Also, if the next word is misspelled neither is highlighted until the first character of the next word is entered. Also, if one continues to misspell words only the the last two misspelled words are highlighted. If user goes to another browser tab or another app and then returns all the words are highlighted until user continues to type then the same behaviour is evident.
![tinymce-browser-spellcheck-issue1](https://github.com/backdrop-contrib/tinymce/assets/6208775/f33ed42c-e443-4e6a-86f0-c6d6449311e1)

**Comment by indigoxela** [comment]
@izmeez  I'm afraid, this is browser behavior, and is nothing, this module can handle. (My browsers behave correctly.)

**Comment by izmeez** [comment]
I have checked with other browsers and they are working fine. I was surprised when I saw this with Firefox browser and the CK4 editor did not behave the same way on that browser. You are correct this is not related to this module. I will have to observe the behaviour more closely. Other than that, this feature appears to be done. Thank you.
