### ISSUE TITLE
Field Size (rows) not working with Tiny MCE

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tinymce#77]
With TinyMCE enabled and used as the text format the body field is smaller than it should be and changing the size of the text field in the field settings has no effect. 

---

Steps to recreate:

1. Create a new Backdrop Site
2. Add a page and note the size of the body field

![image](https://github.com/backdrop-contrib/tinymce/assets/3144571/47aeb0e6-7aa8-45e4-9047-7af3f636d79e)

3. Enable TinyMCE and make it the default text editor for the BASIC text format. Then try to Add a Page again. 

![image](https://github.com/backdrop-contrib/tinymce/assets/3144571/2fd7e181-7627-4288-88a5-d675337a3342)

4. Then go to the Page content type and edit the body field settings to increase the size of the row. Change from 10 to 20. 
![image](https://github.com/backdrop-contrib/tinymce/assets/3144571/cdbf2722-77c7-4a62-ad57-646baa781c94)

5. Now try to create a new page again and notice the text field has not gotten any bigger. 

![image](https://github.com/backdrop-contrib/tinymce/assets/3144571/94e119a3-079c-4dc2-ac9c-c83ef97750dd)

**Comment by indigoxela** [comment]
It doesn't work that way with WYSIWYGs. (Also not for CKE, BTW)

To control the height, use the corresponding dimension settings in a custom profile:

https://www.tiny.cloud/docs/tinymce/latest/editor-size-options/

By default, the **autoresize** plugin's enabled, so the editor starts small and grows with its contents. But you can also turn that off and configure (to detail) in your editor profile. Not via builder, though (too many options, would bloat the admin form).
