### ISSUE TITLE
Use of filters with Tiny MCE

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tinymce#78]
Can anyone suggest a good best practice for which filters to use with TinyMCE?

These are the default filters with CKEditor 5 in the Basic text format. Is this a good place to start?

![image](https://github.com/backdrop-contrib/tinymce/assets/3144571/71c997aa-c39d-41db-96b4-e92d656d3d5b)

**Comment by indigoxela** [comment]
Two filters, that get attached by default, but make no sense at all for *any* sort of WYSIWYG should get disabled (with any editor):

- Convert URLs into links (we can set links as we need)
- Convert line breaks into HTML (ditto)

Both do no harm at all with TinyMCE, but contradict the whole WYSIWYG concept. (They should also get turned off with any other editor, BTW. Shouldn't actually be on by default in the standard filtered_html format anyway, but that's unrelated here.)

**Comment by indigoxela** [comment]
A little more in-depth info: Handling of floated or captioned images is identical to CKE4, so images will only be aligned, if you turn on the corresponding filters on, for example on admin/config/content/formats/filtered_html

A subtle difference:

Unlike CKE5 Tiny will not remove existing captions or alignments in existing content, when opening a node form - after you turned the filter off. You'll still see caption or alignment, *when editing with Tiny*, but not after saving (as the filter is off). CKE5 rips captions out and suppresses alignment. Tiny won't misbehave.
