### ISSUE TITLE
Open the Wiki

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/tinymce#9]
Please can you open the wiki for this project? I have a feeling it will be good to share tips on custom profiles.

**Comment by indigoxela** [comment]
@yorkshire-pudding you're my hero! Do you have access now? Should work. :wink:

**Comment by yorkshire-pudding** [comment]
Thanks @indigoxela - I have access now. Might not get much done until next week as my dad is visiting this weekend.

**Comment by indigoxela** [comment]
@yorkshire-pudding delay doesn't matter, any help with documentation is cool. :wink: Have a nice weekend!
